### ISSUE TITLE
Add mempool persistence logic using Redis

### ISSUE THREAD

**Issue by kristofgazso** [pimlicolabs/alto#13]
NOTE: Lower priority

Currently we don't persist incoming UserOperations in a mempool, and send them straight to be included on-chain. This is not a big problem right now because there isn't enough volume on-chain to justify waiting for multiple UserOperations until submission for inclusion, but this is required to be compliant with the spec.

Let's create a persistent mempool using Redis with `ioredis`

**Comment by kanthgithub** [comment]
can this be done via rocksdb where its key-value pair? 
thinking about redis vs rocksdb terms of  horizontal scalability

**Comment by plusminushalf** [comment]
https://redis.io/docs/data-types/json/

**Comment by mouseless-eth** [comment]
closing as alto now has seperate mempools (Outstanding, Processing, Submitted, nonceQueue) to handle userOperation persistence.

**Comment by kanthgithub** [comment]
@mouseless-eth will be picking this up if this is still relevant change to be done
i was trying to run bundler locally with anvil

**Comment by defistar** [comment]
@mouseless-eth is this still a priority item to be picked up? i have some time this  & next week and can pick this up if this is needed

**Comment by mouseless0x** [comment]
This issue is still relevant and a feature that we will most likely implement in the future, let me know if anyone would like to give it a go. Happy to discuss further in dms at [t.me/mouseless](https://t.me/mouseless)
