### ISSUE TITLE
Fix arbitrum gas calculation

### ISSUE THREAD

**Issue by kristofgazso** [pimlicolabs/alto#14]
Arbitrum calculates gas usage differently than other chains, as explained [here](https://developer.arbitrum.io/devs-how-tos/how-to-estimate-gas). Currently we just hardcode a gas usage multiple, but we should precisely calculate the actual gas limit to use based on Arbitrum's formula.

**Comment by mouseless0x** [comment]
Closing this issue as this has since been implemented
