### ISSUE TITLE
Rewrite config options to use dot notation

### ISSUE THREAD

**Issue by kristofgazso** [pimlicolabs/alto#15]
Currently all the options use names like lokiHost, lokiUsername, lokiPassword, signerPrivateKeys, utilityPrivateKey, maxSigners, etc.

Would be much cleaner to namespace them using dot notation for the configs where it makes sense, so something like loki.host, loki.username, loki.password, signer.privateKeys, signer.utilityKey, signer.maxSigners, etc.

The current config options are mostly written under `packages/cli/src`

**Comment by sumitshinde-84** [comment]
@kristofgazso I would like to work on this issue , can you please assign it to me?

**Comment by kristofgazso** [comment]
Will do as soon as I get back to my computer!

Thanks for taking it up!

**Comment by sumitshinde-84** [comment]
I am about resolve   it , if you dont mind can I submit pull request

**Comment by kristofgazso** [comment]
Of course, feel free to submit it

**Comment by sumitshinde-84** [comment]
Hi there I've submitted a pull request for the changes I made and I would really appreciate it if you could take some time to review it. Your feedback would be invaluable to help me improve the code and ensure that it's in line with the project's standards. Let me know if you have any questions or concerns. Thanks!

**Comment by sumitshinde-84** [comment]
@kristofgazso please review my pull request

**Comment by mouseless0x** [comment]
Closing this issue as the Alto configurations have been reworked/improved in #178 (adding namespaces to config flags) and #326 (global config support in Alto)
