### ISSUE TITLE
Gas limit estimation is broken by go-ethereum@1.13.5

### ISSUE THREAD

**Issue by nksazonov** [pimlicolabs/alto#160]
## Description

We are running Alto in a container locally alongside geth node as an infra for our AA tests. After switching to newer versions of go-ethereum, we have noticed that Alto is failing to estimate the `callGasLimit` properly.

## To Reproduce

1. Start up geth locally
2. Deploy infra contracts (EntryPoint, SW, SW Factory etc)
3. Start Alto locally, supplying the EntryPoint and other necessary info
4. All `eth_estimateUserOperationGas` calls result in callGasLimit estimated to 9000, which leads to OOG errors in userop execution.

## Expected behavior

Alto estimates callGasLimit correctly, so that userop is executed successfuly.

## Versions
 - OS: macOS v14.1.2
 - Alto: v1.0.1, with  `balanceOverride = false`
 - Go-ethereum: 1.13.14
 - Geth node: without `eth_call` overrides support

## Reason

We have found that a magic number `9000` is used when estimated `callGasLimit` is lower than 9000. Given our geth and Alto settings, [Alto uses `viem` to call `EntryPoint.simulateHandleOp`](https://github.com/pimlicolabs/alto/blob/v1.0.1/packages/rpc/src/validation/validator.ts#L235-L251), which does NOT set `gasPrice`, `feePerGas` and `priorityFeePerGas` to `eth_call` call.

Go-ethreum@1.13.5 introduced [a change to `block.basefee` logic in the vm](https://github.com/ethereum/go-ethereum/pull/28470) in the `eth_call`, `eth_estimateGas` etc. contexts: if `gasPrice` is not specified, then `block.basefee` returns 0. This is very important for the Alto Bundler, because its gas estimation depends on `EntryPoint.simulateHandleOp`, which uses `block.basefee`.

Currently, without specifying `gasPrice` when calling `EntryPoint.simulateHandleOp`, it returns `paid` equal to `gasUsed * maxPriorityFeePerGas` (without adding `block.baseFee`), which [results in `callGasLimit` calculated to ~`-1500000`](https://github.com/pimlicolabs/alto/blob/v1.0.1/packages/rpc/src/rpcHandler.ts#L369-L386).

## Fix

[As specified in the go-ethereum PR](https://github.com/ethereum/go-ethereum/pull/28470#issuecomment-1846703536), specifying `gasPrice` in `eth_call` is sufficient. Indeed, after changing

```ts
const errorResult = await entryPointContract.simulate
    .simulateHandleOp(
        [
            userOperation,
            "0x0000000000000000000000000000000000000000",
            "0x"
        ],
        {
            account: this.utilityWallet
        }
    )
```

in [`packages/rpc/src/validation/validator.ts`](https://github.com/pimlicolabs/alto/blob/v1.0.1/packages/rpc/src/validation/validator.ts#L235-L245) to

```ts
const errorResult = await entryPointContract.simulate
    .simulateHandleOp(
        [
            userOperation,
            "0x0000000000000000000000000000000000000000",
            "0x"
        ],
        {
            account: this.utilityWallet,
            gasPrice: userOperation.maxFeePerGas,
            feePerGas: userOperation.maxFeePerGas,
            priorityFeePerGas: userOperation.maxPriorityFeePerGas,
        }
    )
```

Alto's gas limit estimation works as expected.

We hope you can incorporate this fix, as we use Alto heavily in our workflow.

**Comment by kristofgazso** [comment]
Thanks for this! Would you be able to try with the main branch?

**Comment by nksazonov** [comment]
It works!
Strange, I have checked the code in `main` branch before opening the issue, and as I have not found the explicit fix, I have not run the Bundler.
Could you point out to why it works now, please? :)

**Comment by mouseless0x** [comment]
Closing this issue as it seems resolved now, feel free to add a comment below if this is not the case
