### ISSUE TITLE
Safe Account with custom ERC1271 owner contract may bypass EIP7562 storage validation rules

### ISSUE THREAD

**Issue by ernestognw** [pimlicolabs/alto#260]
**Describe the bug**

So far, according to EIP-7562, arbitrary storage access is forbidden unless some requirements are met. One of this is that read-only storage in non-entity contracts is allowed only if the entity is staked:

> If the entity (paymaster, factory) is staked, then it is also allowed:
> ...
> - [STO-033] Read-only access to any storage in non-entity contract.

The issue (not sure if a bug or a feature) is that I've been playing with the idea of using ERC-1271 to set smart contract owners of smart contract wallets and I'm not sure whether the bundler allows for bypassing the storage validation rules. 

Particularly, I've been using the ERC4337 module for Safe, which supports `isValidSignature` through their [`checkSignatures` method](https://github.com/safe-global/safe-modules/blob/main/modules/4337/contracts/Safe4337Module.sol#L225) that eventually [checks the contract signature](https://github.com/safe-global/safe-smart-account/blob/v1.4.1/contracts/Safe.sol#L315). This way I've been using a custom smart contract signer similar to the following:

```solidity
contract P256Identity is IERC1271 {
    using P256 for bytes32;

    // bytes4(keccak256("isValidSignature(bytes,bytes)")
    bytes4 internal constant EIP1271_MAGIC_VALUE = 0x20c13b0b;

    struct PublicKey {
        bytes32 qx;
        bytes32 qy;
    }

    PublicKey publicKey;

    constructor(bytes32 qx, bytes32 qy) {
        publicKey = PublicKey(qx, qy);
    }

    function isValidSignature(
        bytes32 digest,
        bytes memory signature
    ) external view returns (bytes4) {
        return
            _verifyP256Identity(digest, signature)
                ? EIP1271_MAGIC_VALUE
                : bytes4(0);
    }

    function _verifyP256Identity(
        bytes32 digest,
        bytes memory signature
    ) internal view returns (bool) {
        PublicKey memory pubKey = publicKey();

        (uint256 r, uint256 s) = _splitSignature(signature);

        if (normalize) {
            digest = sha256(abi.encode(digest));
        }

        return digest.verify(digest, r, s, pubKey.qx, pubKey.qy);
    }
    function _splitSignature(
        bytes memory signature
    ) private pure returns (uint256 r, uint256 s) {
        r = uint256(bytes32(signature[00:31]));
        s = uint256(bytes32(signature[32:63]));
    }
}
```

After testing it out a couple of times (here's a [test tx in Arbitrum](https://sepolia.arbiscan.io/tx/0x924257e84890082d39daeb9c34bd5839a559b13be06a93cb7597f6a58f59c6d5)) it's been working fine so far but I can't reason why. 

The rationale of the validation rules is that it shouldn't be possible to create spam UserOperations (i.e. that fail due to a storage change), although that's impossible for this tiny contract (because storage can't be changed) then it should be possible to craft an operation that does change storage between the validation and execution.

**To Reproduce**

Reproducing the transaction I shared is quite difficult as it requires a custom off-chain signer, but here's the execution diagram according to the test tx I'm sharing: https://sepolia.arbiscan.io/tx/0x924257e84890082d39daeb9c34bd5839a559b13be06a93cb7597f6a58f59c6d5

```mermaid
sequenceDiagram
    EntryPoint ->> SafeWallet1.4.1: validateUserOp()
    SafeWallet1.4.1 ->> P256Identity: isValidSignature()
    P256Identity -->> P256Identity: sload public key slots
    Note right of P256Identity: Aren't validation rules violated here?
    P256Identity ->> SafeWallet1.4.1: success
    SafeWallet1.4.1 ->> EntryPoint: success
```

**Expected behavior**

Not sure whether it should be possible in the first place.

**Additional Context**

Seems like the corresponding rules is enabled:
https://github.com/pimlicolabs/alto/blob/a848d11011042a146b9152e7be493dc163f4208b/src/rpc/validation/TracerResultParserV07.ts#L615-L616

**Comment by plusminushalf** [comment]
Our bundler can be run with safe mode enabled or disabled. Safe mode makes sure that all the validation rules are met as per the standard. Our bundler services are running with safe mode disabled for private transactions, and will accept and bundle these user operations right now. But as the decentralised mempool goes live those ops will not be sent over to p2p.

**Comment by ernestognw** [comment]
Yeah I saw the safe mode but wasn't clear whether it was enabled or not but now it's clearer.

Could you elaborate on the decentralized mempool? Essentially, we'd like the guarantee that our accounts won't stop working suddenly.

Will there be a way of opt-in for private transactions always? Currently, the workaround is to use immutable args but it'd save some time if we can just release and be sure it'll work under certain conditions.

Thanks for your answer!
