### ISSUE TITLE
Custom EVM Support

### ISSUE THREAD

**Issue by cristianopolicarpo** [pimlicolabs/alto#34]
Hello guys,

Is there any guide on how to deploy this bundler in custom EVM networks?

**Comment by mouseless-eth** [comment]
deploying to a custom EVM network is just a matter of running the bundler with configs for that specific network (rpc, entrypoint, ...)

```
pnpm build
./alto --rpcUrl <...> --entryPoint <...> --signerPrivateKeys <...> ...
```
