### ISSUE TITLE
Unable to run test:spec

### ISSUE THREAD

**Issue by ManasNagaraj** [pimlicolabs/alto#5]
` root@0.0.1 test:spec`
` ./test/run-spec-tests.sh`
`====================================================================`
`====== alto-launcher.sh`
`====================================================================`
`./test/run-spec-tests.sh: line 35: /Users/fallenangel/pimlico/alto/spec-tests/alto-launcher.sh: No such file or directory
`

OS: macOS

**Comment by kristofgazso** [comment]
Your fix has been included, closing this issue for now!
