### ISSUE TITLE
[Help] Unable to estimateUserOperationGas

### ISSUE THREAD

**Issue by Troublor** [pimlicolabs/alto#63]
Hi, very appreciate this great work. 
However, I am trying to use alto on a local testnet and could not make `estimateUserOperation` json-rpc work. The error message is: `Cannot decode zero data ("0x") with ABI parameters.`. 

I investigated the code of alto and found that alto seems to call `callExecute` function in `EntryPoint` address during `simulateHandleOp`: 

https://github.com/pimlicolabs/alto/blob/adb3696a43e4a03460d6e0ae1fac687d51c5cc26/packages/rpc/src/gasEstimation.ts#L197-L205

I don't think there is a function called `callExecute` in the entrypoint. Then I notice there is a special parameter in the RPC parameters called `finalParam`, which seems to instruct the RPC backend to replace the bytecode of entrypoint to a given `ExecuteSimulator` code.

https://github.com/pimlicolabs/alto/blob/adb3696a43e4a03460d6e0ae1fac687d51c5cc26/packages/rpc/src/gasEstimation.ts#L24-L59

Is this contract bytecode replacement feature in the Ethereum JSON-RPC standard? Or are you using a customized Ethereum node to handle such RPCs? How can I make this work on a local testnet (e.g., anvil)?

**Comment by mouseless-eth** [comment]
bytecode replacement is part of the Ethereum JSON-RPC spec (using StateOverrides). However not all rpc providers allow state overrides. 

Anvil does support code overrides but if your rpc doesn't then you can run alto with the `--noEthCallOverrideSupport` flag
