### ISSUE TITLE
Alto Bundler local run - Issue/Instruction updates

### ISSUE THREAD

**Issue by kanthgithub** [pimlicolabs/alto#72]
**Describe the bug**
Detailed steps to Run bundler with command line arguments
current instruction in readme guide doesn't mention about passing command line args (yargs) 

it gives 

```sh
./alto
```

this runs in to error:

```
> root@0.0.1 start /Users/kanth/Documents/defi/account-abstraction/pimlico/alto
> node packages/cli/lib/alto.js run

 ✖ Missing required arguments: entryPoint, signerPrivateKeys, utilityPrivateKey, minBalance, rpcUrl
```

**Suggestion**
1. For local run need steps to deploy `entryPoint` on geth node / hardhat node

It would be nice to have instructions:
1. run geth node
2. deploy essential contracts on geth/local node
3. capture the privateKeys of local node which can be signerPrivateKey

@plusminushalf

**Comment by kanthgithub** [comment]
** would like to run the bundler on local machine and contribute to let persist mempool on redis from local-memory
** refactor executor to make it more modular

**Comment by kanthgithub** [comment]
@plusminushalf hi sorry for delayed response. i will betrying on anvil and update here
its much easier to develop enhancements locally on anvil

**Comment by mouseless-eth** [comment]
we now have a bashscript to help setup a local alto instance connected to a local anvil node (where all necessary contracts will be deployed locally). Readme on how to run this bashscript can be found at [scripts/](https://github.com/pimlicolabs/alto/tree/main/scripts).

**Comment by kanthgithub** [comment]
@mouseless-eth thanks will try it today so that i can test a basic flow of userOps submission
